<?php

//Add more view modes for content type displays
function agora_viewmodes_entity_info_alter(&$entity_info)
{
    $entity_info['node']['view modes']['front_mode_1'] = [
        'label'           => t('Front - Mode 1'),
        'custom settings' => true,
    ];
    
    $entity_info['node']['view modes']['front_mode_2'] = [
        'label'           => t('Front - Mode 2'),
        'custom settings' => true,
    ];
    
    $entity_info['node']['view modes']['navbar'] = [
        'label'           => t('Navbar'),
        'custom settings' => true,
    ];
    
    $entity_info['node']['view modes']['related'] = [
        'label'           => t('Related'),
        'custom settings' => true,
    ];
    
    $entity_info['taxonomy_term']['view modes']['teaser'] = [
        'label'           => t('Teaser'),
        'custom settings' => true,
    ];
}