<?php

/**
 * @return array
 */
function agoranav_theme()
{
    return [
        'agoranav_newstopic' => [
            'template' =>  'agoranav_newstopic',
            'pattern'   => 'agoranav_newstopic__',
            'variables' => [
                'title' =>                  NULL,
                'topic_id' =>               NULL,
                'topic_class' =>            NULL,
                'bgimage' =>                NULL,
                'elements_nl_last' =>       [],
                'elements_nl_all' =>        [],
                'elements_topics' =>        [],
            ],
        ],
        'agoranav_newsletter' => [
            'template' =>  'agoranav_newsletter',
            'pattern'   => 'agoranav_newsletter__',
            'variables' => [
                'title' =>                  NULL,
                'date' =>                   NULL,
                'bgimage' =>                NULL,
                'backlink' =>               NULL,
                'elements_nl_last' =>       [],
                'elements_nl_all' =>        [],
                'elements_topics' =>        [],
            ],
        ],
        'agoranav_article' => [
            'template' =>  'agoranav_article',
            'pattern'   => 'agoranav_article__',
            'variables' => [
                'backlink' =>       NULL,
                'issue' =>          NULL,
                'article_title' =>  NULL,
                'customlink1' =>    NULL,
            ],
        ],
        'agoranav_generic' => [
            'template' =>  'agoranav_generic',
            'pattern'   => 'agoranav_generic__',
            'variables' => [
                'pagevars' =>       NULL,
                'settings' =>       NULL,
            ],
        ],
    ];
}

/**
 * @param array $vars
 */
function agoranav_preprocess_agoranav_generic(&$vars)
{
    $obj = menu_get_object();
    if($obj && is_object($obj))
    {
        if(isset($obj->nid))
        {
            $vars['theme_hook_suggestions'][] = 'agoranav_generic__' . $obj->nid;
        }
    }
    //dpm($vars['theme_hook_suggestions'], "AGORANAV-GENERIC");
}

/**
 * @param array $vars
 */
function agoranav_preprocess_agoranav_article(&$vars)
{
    $obj = menu_get_object();
    if($obj && is_object($obj))
    {
        if(isset($obj->type))
        {
            $vars['theme_hook_suggestions'][] = 'agoranav_article__' . $obj->type;
        }
    }
    //dpm($vars['theme_hook_suggestions'], "AGORANAV-ARTICLE");
}

/**
 * @param array $vars
 */
function agoranav_preprocess_agoranav_newsletter(&$vars)
{
    $obj = menu_get_object();
    if($obj && is_object($obj))
    {
        if(isset($obj->type))
        {
            $vars['theme_hook_suggestions'][] = 'agoranav_newsletter__' . $obj->type;
        }
    }
    //dpm($vars['theme_hook_suggestions'], "AGORANAV-ARTICLE");
}
