<?php

/**
 * @return array
 */
function agoranav_theme()
{
    return [
        'agoranav_newsletter' => [
            'template' =>  'agoranav_newsletter',
            'pattern'   => 'agoranav_newsletter__',
            'variables' => [
                'number' =>         NULL,
                'date' =>           NULL,
            ],
        ],
        'agoranav_article' => [
            'template' =>  'agoranav_article',
            'pattern'   => 'agoranav_article__',
            'variables' => [
                'backlink' =>       NULL,
                'issue' =>          NULL,
                'article_title' =>  NULL,
                'customlink1' =>    NULL,
            ],
        ],
        'agoranav_generic' => [
            'template' =>  'agoranav_generic',
            'pattern'   => 'agoranav_generic__',
            'variables' => [
                'pagevars' =>       NULL,
                'settings' =>       NULL,
            ],
        ],
    ];
}

/**
 * @param array $vars
 */
function agoranav_preprocess_agoranav_generic(&$vars)
{
    $obj = menu_get_object();
    if($obj && is_object($obj))
    {
        if(isset($obj->nid))
        {
            $vars['theme_hook_suggestions'][] = 'agoranav_generic__' . $obj->nid;
        }
    }
    //dpm($vars['theme_hook_suggestions'], "AGORANAV-GENERIC");
}

/**
 * @param array $vars
 */
function agoranav_preprocess_agoranav_article(&$vars)
{
    $obj = menu_get_object();
    if($obj && is_object($obj))
    {
        if(isset($obj->type))
        {
            $vars['theme_hook_suggestions'][] = 'agoranav_article__' . $obj->type;
        }
    }
    //dpm($vars['theme_hook_suggestions'], "AGORANAV-ARTICLE");
}
