<?php

/**
 * Generic node(all types) edit form hook
 *
 * @param array $form
 * @param array $form_state
 */
function agora_nodeformauto_form_node_form_alter(&$form, $form_state)
{
    if($form["#bundle"] == "newsletter")
    {
        ___agora_nodeformauto_newletter_edit_form_alter($form, $form_state);
    }
}

/**
 * @param array $form
 * @param array$form_state
 */
function ___agora_nodeformauto_newletter_edit_form_alter(&$form, $form_state)
{
    //new node
    if(!$form["nid"]["#value"])
    {
        // Auto numbering
        $number = ___agora_nodeformauto_get_new_newsletter_number();
        $form["title_field"][LANGUAGE_NONE][0]["value"]["#default_value"] = $number;
    }
    $form["title_field"][LANGUAGE_NONE][0]["value"]["#attributes"]["readonly"] = "readonly";
}

/**
 * @return int
 */
function ___agora_nodeformauto_get_new_newsletter_number()
{
    $sql = 'SELECT n.title FROM {node} n WHERE n.type = :type ORDER BY n.created DESC LIMIT 1';
    $params = [
        ':type' => 'newsletter',
    ];
    $result = db_query($sql, $params);
    $num = (int) $result->fetchField() + 1;
    return $num;
}